DROP TABLE IF EXISTS images;
CREATE TABLE images (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	path VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,
	cdate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);